# Generated by Django 4.2.5 on 2023-10-16 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TextUtill', '0003_userotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userotp',
            name='otp',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
