# Generated by Django 4.2.5 on 2023-10-16 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TextUtill', '0004_alter_userotp_otp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserOTP',
        ),
    ]
